[package]
name = "engine_core"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ash.workspace = true
ash-window.workspace = true
anyhow.workspace  = true
egui.workspace = true
egui_extras.workspace = true
egui-winit.workspace = true
egui-ash-renderer.workspace = true
gltf.workspace = true
nalgebra.workspace  = true
macros = { path = "../macros" }
rand.workspace = true
inventory = "0.3.24"
walkdir.workspace = true
winit.workspace = true
