[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[dependencies]
engine_core = { path = "../engine_core" }
game_data = { path = "../game_data" }
renet.workspace = true 
bincode.workspace = true 
serde.workspace = true
anyhow.workspace = true
nalgebra.workspace = true

renet_netcode.workspace = true
