[package]
name = "editor"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "editor"
path = "src/main.rs"

[dependencies]
engine_core = { path = "../engine_core" }
game_data = { path = "../game_data" }
anyhow.workspace = true
winit.workspace = true
hot-lib-reloader.workspace = true
libloading.workspace = true
